# main text of home
name: Waverly (Linqing) Wei
bio: PhD student in biostatistics at UC Berkeley

# twitter summary info
description: 

picture: assets/images/picture.jpg

url: https://waverlywei.github.io/
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
github: WaverlyWei
email: linqing_wei@berkeley.edu

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
